# secp256k1-jdk Dependabot updates for Maven and Nix
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      # Stay on the current MAJOR.MINOR release train for GraalVM SDK
      - dependency-name: "org.graalvm.sdk*"
        update-types: [ "version-update:semver-minor", "version-update:semver-major" ]

  - package-ecosystem: "nix"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
