# Build on minimal Nix image using the devshell from `flake.nix`
nix-devshell:
  timeout: 3h   # long timeout in case of unexpected rebuilds of packages from source
  image: nixos/nix:latest
  variables:
    NIXPKGS_URL: "github:NixOS/nixpkgs/nixos-unstable"
  before_script:
    # Configure Nix to use a binary cache and enable experimental features
    - nix-env -iA nixpkgs.cachix
    - cachix use nix-community
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix develop .#minimum -c mvn verify -Prun-schnorr,run-ecdsa,run-schnorr-kotlin,run-ecdsa-kotlin
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - /nix/store

# Build on Trixie using a Nix devshell.
trixie-devshell:
  image: debian:trixie-slim
  before_script:
    - apt-get update
    - apt-get -y install nix-setup-systemd
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix develop .#minimum -c mvn verify -Prun-schnorr,run-ecdsa,run-schnorr-kotlin,run-ecdsa-kotlin

# Build on Forky using a Nix devshell.
forky-devshell:
  image: debian:forky-slim
  before_script:
    - apt-get update
    - apt-get -y install nix-setup-systemd
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix develop .#minimum -c mvn verify -Prun-schnorr,run-ecdsa,run-schnorr-kotlin,run-ecdsa-kotlin

# Build on Trixie using Debian's OpenJDK 25, Maven and libsecp256k1.
trixie-maven:
  image: debian:trixie-slim
  before_script:
    - apt-get update
    - apt-get -y install openjdk-25-jdk-headless maven libsecp256k1-2 libsecp256k1-dev
  script:
    - export REVISION=$(mvn -q help:evaluate -Dexpression=revision -DforceStdout)
    - export CI_REVISION=$(echo "$REVISION" | sed 's/-SNAPSHOT$/-ci/')
    - echo "CI_REVISION=$CI_REVISION"
    - export LIBSECP_DIR=$(dirname $(dpkg -L libsecp256k1-2 | grep -E '/libsecp256k1\.so\.[0-9]+$'))
    - echo "LIBSECP_DIR=$LIBSECP_DIR"
    - mvn verify -Prun-schnorr,run-ecdsa,run-schnorr-kotlin,run-ecdsa-kotlin
    - mvn -Drevision="$CI_REVISION" deploy
    - sha256sum target/repo/org/bitcoinj/secp/secp-*/*/*.jar target/repo/org/bitcoinj/secp/secp-*/*/*.pom


# Build on Forky using Debian's OpenJDK 25, Maven and libsecp256k1.
forky-maven:
  image: debian:forky-slim
  before_script:
    - apt-get update
    - apt-get -y install openjdk-25-jdk-headless maven libsecp256k1-6 libsecp256k1-dev
  script:
    - export LIBSECP_DIR=$(dirname $(dpkg -L libsecp256k1-6 | grep -E '/libsecp256k1\.so\.[0-9]+$'))
    - echo "LIBSECP_DIR=$LIBSECP_DIR"
    - mvn verify -Prun-schnorr,run-ecdsa,run-schnorr-kotlin,run-ecdsa-kotlin

stages:
  - test

sast:
  stage: test

include:
  - template: Jobs/SAST.gitlab-ci.yml
