# Build on NixOS using the devshell from `flake.nix` and secp256k1 installed via `nix profile install`
nixos-devshell:
  timeout: 3h   # long timeout because there is no cached build of graalvm-oracle_25-ea
  image: nixos/nix:latest
  variables:
    NIXPKGS_URL: "github:NixOS/nixpkgs/nixos-unstable"
  before_script:
    # Configure Nix to use a binary cache and enable experimental features
    - nix-env -iA nixpkgs.cachix
    - cachix use nix-community
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix profile install nixpkgs#secp256k1
  script:
    - nix develop .#minimum -c gradle -PjavaToolchainVersion=25 build run runEcdsa
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - /nix/store
      - ~/.gradle/

# Build on Trixie using Nix to install OpenJDK 24 and secp256k1 with Gradle installed via the Wrapper.
trixie-gradlew:
  image: debian:trixie-slim
  before_script:
    - apt-get update
    - apt-get -y install nix-setup-systemd
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix profile install nixpkgs#secp256k1
    - NIXPKGS_ALLOW_UNFREE=1 nix profile install github:nixpkgs-jdk-ea/nixpkgs/jdk-ea-25#graalvmPackages.graalvm-oracle_25-ea --impure
  script:
    - export JAVA_HOME=$(NIXPKGS_ALLOW_UNFREE=1 nix eval --raw nixpkgs#graalvmPackages.graalvm-oracle_25-ea.outPath --impure)
    - ./gradlew build run runEcdsa

# Build on Forky using Debian's OpenJDK 25, Gradle via the Wrapper and secp256k1 installed via `nix profile install`.
# If we're lucky, Forky might even get a Debian Gradle we can use. If so, we can make a Forky build that doesn't need Nix.
forky-gradlew:
  image: debian:forky-slim
  before_script:
    - apt-get update
    - apt-get -y install openjdk-25-jdk-headless nix-setup-systemd
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - nix profile install nixpkgs#secp256k1
  script:
    - ./gradlew -PjavaToolchainVersion=25 build run runEcdsa
