# Build on minimal Nix image using the devshell from `flake.nix`
nix-devshell:
  timeout: 3h   # long timeout in case of unexpected rebuilds of packages from source
  image: nixos/nix:latest
  variables:
    NIXPKGS_URL: "github:NixOS/nixpkgs/nixos-unstable"
  before_script:
    # Configure Nix to use a binary cache and enable experimental features
    - nix-env -iA nixpkgs.cachix
    - cachix use nix-community
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix develop .#minimum -c gradle build run runEcdsa
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - /nix/store
      - ~/.gradle/

# Build on Trixie using a Nix devshell.
trixie-devshell:
  image: debian:trixie-slim
  before_script:
    - apt-get update
    - apt-get -y install nix-setup-systemd
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix develop .#minimum -c gradle build run runEcdsa

# Build on Forky using a Nix devshell.
forky-devshell:
  image: debian:forky-slim
  before_script:
    - apt-get update
    - apt-get -y install nix-setup-systemd
    - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  script:
    - nix develop .#minimum -c gradle build run runEcdsa
