[project]
name = "secp256k1-jdk"

[project.languages.java]
groupId = "org.bitcoinj.secp"
version = "9"      # Minimum Java version for use of secp256k1-jdk

[release.github]
owner = "bitcoinj"
name = "secp256k1-jdk"
enabled = false

[signing]
active = "ALWAYS"

[signing.pgp]
armored = true
mode = "COMMAND"

[signing.pgp.command]
executable = "gpg"
defaultKeyring = true

[deploy.maven.mavenCentral.sonatype]
active = "ALWAYS"
url = "https://central.sonatype.com/api/v1/publisher"
applyMavenCentralRules = true
stagingRepositories = ["target/repo-signed"]
