= secp256k1-java

`secp256k1-java` is a wrapper around https://github.com/bitcoin-core/secp256k1[libsecp256k1], a C
library implementing various cryptographic functions using the https://www.secg.org/[SECG] curve
https://en.bitcoin.it/wiki/Secp256k1[secp256k1].

== Building Headers with Nix

NOTE:: These instructions assume you are using `experimental-features = nix-command flakes`.

WARNING:: This is a work-in-progress by a Nix beginner.

. nix develop
. ./extract-headers.sh

== Building with Gradle Wrapper

If necessary copy updated, extracted headers into `src/main/java/org/consensusj/secp256k1/`

. `./gradlew build`

== Running with Gradle Wrapper

(This assumes a specific version of secp256k1 was installed with nixpkgs)

. `./gradlew -PjavaPath="/nix/store/j9mf1fh4wbb8c3x1zwqfs218bhml1rbw-secp256k1-0.4.0/lib/" run`

== Building with Nix

WARNING: This doesn't work yet

. `nix develop`
. `gradle build`

== Other Java Implementations

* bitcoin-s fork https://bitcoin-s.org/docs/secp256k1/jni-modify
* Kotlin multiplatform wrapper: https://github.com/acinq/secp256k1-kmp

== Reporting a vulnerability

See SECURITY.adoc (TBD)
