// Generated by jextract

package org.consensusj.secp256k1;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("secp256k1_context_static", RuntimeHelper.POINTER);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("secp256k1_context_no_precomp", RuntimeHelper.POINTER);
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "secp256k1_selftest",
        constants$1.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "secp256k1_context_create",
        constants$1.const$4
    );
}


