// Generated by jextract

package org.consensusj.secp256k1;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("secp256k1_nonce_function_bip340", RuntimeHelper.POINTER);
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(4, JAVA_BYTE).withName("magic"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("noncefp"),
        RuntimeHelper.POINTER.withName("ndata")
    ).withName("secp256k1_schnorrsig_extraparams");
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(secp256k1_schnorrsig_extraparams.noncefp.class, "apply", constants$12.const$2);
    static final VarHandle const$3 = constants$13.const$1.varHandle(MemoryLayout.PathElement.groupElement("noncefp"));
    static final VarHandle const$4 = constants$13.const$1.varHandle(MemoryLayout.PathElement.groupElement("ndata"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "secp256k1_schnorrsig_sign32",
        constants$13.const$5
    );
}


