// Generated by jextract

package org.consensusj.secp256k1;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "secp256k1_ecdsa_signature_parse_compact",
        constants$4.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "secp256k1_ecdsa_signature_parse_der",
        constants$4.const$1
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "secp256k1_ecdsa_signature_serialize_der",
        constants$5.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "secp256k1_ecdsa_signature_serialize_compact",
        constants$4.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "secp256k1_ecdsa_verify",
        constants$5.const$2
    );
}


