// Generated by jextract

package org.consensusj.secp256k1;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct secp256k1_scratch_space_struct secp256k1_scratch_space;
 * }
 */
public final class secp256k1_scratch_space {

    // Suppresses default constructor, ensuring non-instantiability.
    private secp256k1_scratch_space() {}
}


