// Generated by jextract

package org.bitcoinj.secp256k1.foreign.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(64, JAVA_BYTE).withName("data")
    ).withName("secp256k1_xonly_pubkey");
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(96, JAVA_BYTE).withName("data")
    ).withName("secp256k1_keypair");
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "secp256k1_xonly_pubkey_parse",
        constants$4.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "secp256k1_xonly_pubkey_serialize",
        constants$4.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "secp256k1_xonly_pubkey_cmp",
        constants$4.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "secp256k1_xonly_pubkey_from_pubkey",
        constants$5.const$2
    );
}


