// Generated by jextract

package org.bitcoinj.secp256k1.foreign.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "secp256k1_ecdsa_signature_normalize",
        constants$4.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(secp256k1_nonce_function_rfc6979.class, "apply", constants$0.const$2);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("secp256k1_nonce_function_rfc6979", RuntimeHelper.POINTER);
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(secp256k1_nonce_function_default.class, "apply", constants$0.const$2);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("secp256k1_nonce_function_default", RuntimeHelper.POINTER);
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(secp256k1_ecdsa_sign$noncefp.class, "apply", constants$0.const$2);
}


