// Generated by jextract

package org.bitcoinj.secp256k1.foreign.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(64, JAVA_BYTE).withName("data")
    ).withName("secp256k1_pubkey");
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(64, JAVA_BYTE).withName("data")
    ).withName("secp256k1_ecdsa_signature");
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(secp256k1_nonce_function.class, "apply", constants$0.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$0.const$2
    );
    static final VarHandle const$5 = RuntimeHelper.POINTER.varHandle();
}


