// Generated by jextract

package org.bitcoinj.secp256k1.foreign.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "secp256k1_ec_privkey_tweak_mul",
        constants$4.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "secp256k1_ec_pubkey_tweak_mul",
        constants$4.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "secp256k1_context_randomize",
        constants$7.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "secp256k1_ec_pubkey_combine",
        constants$4.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "secp256k1_tagged_sha256",
        constants$9.const$4
    );
}


