// Generated by jextract

package org.bitcoinj.secp256k1.foreign.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * typedef struct secp256k1_context_struct secp256k1_context;
 * }
 */
public final class secp256k1_context {

    // Suppresses default constructor, ensuring non-instantiability.
    private secp256k1_context() {}
}


