name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        distribution: ['temurin']
      fail-fast: false
    name: ${{ matrix.os }} JDK 23
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          # When installing multiple JDKs, the last JDK installed is the default and will be used to run Gradle itself
          java-version: |
            23
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install secp256k1 with Nix
        run: nix profile install nixpkgs#secp256k1
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Java & Kotlin Examples
        run: ./gradlew run runEcdsa
